### ISSUE TITLE
Множество будильников

### ISSUE THREAD

**Issue by swissdeam** [swissdeam/TimeMachine#3]
Реализовать функционал будильника:

1. Функция выбора часа и минуты, когда должен сработать будильник
2. Кнопка включения-выключения будильника
3. Отображение сколько часов и минут осталось до срабатывания будильника
4. Сигнал будильника (можно реализовать в любом графическом виде(смена цвета фона например)
5. Кнопка остановки сигнала будильник

Реализовать возможность постановки нескольких будильников

**Comment by beevasya** [comment]
Выполнено
